name: Deploy Landing Robust

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repo (opcional, sirve para comprobar que Actions funciona)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Deploy completo vía SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "=== Iniciando despliegue ==="
            cd /opt/landing/lumensm-landing-boltai

            # Hacer pull de la rama main
            git fetch --all
            git reset --hard origin/main

            # Instalar dependencias y build
            npm ci
            npm run build

            # Backup de la versión actual
            TARGET="/opt/landing/lumensm-landing-boltai/dist"
            BACKUP="/opt/landing/lumensm-landing-boltai/dist_backup_$(date +%Y%m%d%H%M%S)"
            if [ -d "$TARGET" ]; then
              echo "Creando backup de la versión actual en $BACKUP"
              mv "$TARGET" "$BACKUP"
            fi

            # Crear carpeta nueva y copiar build
            mkdir -p "$TARGET"
            cp -r ./dist/* "$TARGET/"

            echo "Despliegue completado con éxito."

            # Limpiar backups antiguos (mantener solo los últimos 5)
            echo "Limpiando backups antiguos..."
            ls -dt /opt/landing/lumensm-landing-boltai/dist_backup_* | tail -n +6 | xargs -r rm -rf
            echo "Backups antiguos eliminados."
            echo "=== Fin de despliegue ==="
