name: Deploy Landing Robust
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "=== Iniciando despliegue ==="
            cd /opt/landing/lumensm-landing-boltai
            git fetch --all
            git reset --hard origin/main
            npm ci
            npm run build
            echo "Archivos en dist:"
            ls -l ./dist
            echo "Despliegue completado con éxito."
