name: Deploy Landing Robust

on:
  push:
    branches:
      - main  # rama que dispara el deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.8'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          cd /opt/landing/lumensm-landing-boltai
          npm ci

      # 4. Build
      - name: Build
        run: |
          cd lumensm-landing-boltai
          npm run build

      # 5. Deploy con backup, rollback y limpieza de backups antiguos
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            TARGET="/opt/landing/lumensm-landing-boltai/dist"
            BACKUP="/opt/landing/lumensm-landing-boltai/dist_backup_$(date +%Y%m%d%H%M%S)"

            echo "=== Iniciando despliegue ==="

            # Backup de la versión actual
            if [ -d "$TARGET" ]; then
              echo "Creando backup de la versión actual en $BACKUP"
              mv "$TARGET" "$BACKUP"
            fi

            # Crear carpeta nueva
            mkdir -p "$TARGET"

            # Sincronizar los archivos nuevos
            rsync -avz --delete ~/lumensm-landing-boltai/dist/ "$TARGET/"
            if [ $? -ne 0 ]; then
              echo "Error en despliegue. Restaurando backup..."
              rm -rf "$TARGET"
              mv "$BACKUP" "$TARGET"
              exit 1
            fi

            echo "Despliegue completado con éxito."

            # Limpiar backups antiguos (mantener solo los últimos 5)
            echo "Limpiando backups antiguos..."
            ls -dt /opt/landing/lumensm-landing-boltai/dist_backup_* | tail -n +6 | xargs -r rm -rf
            echo "Backups antiguos eliminados."

            echo "=== Fin de despliegue ==="
