name: Deploy Landing Robust
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository in GitHub runner
        uses: actions/checkout@v3

      - name: Deploy to server with detailed debug
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "=== Inicio Despliegue ==="

            echo "1. Entrando en carpeta del proyecto"
            cd /opt/landing/lumensm-landing-boltai || { echo 'ERROR: No se pudo entrar al directorio'; exit 1; }

            echo "2. Estado actual del repo antes del fetch"
            git status

            echo "3. Ejecutando git fetch --all"
            git fetch --all || { echo 'ERROR: git fetch fall贸'; exit 1; }

            echo "4. Reseteando al origen main"
            git reset --hard origin/main || { echo 'ERROR: git reset fall贸'; exit 1; }

            echo "5. Estado actual del repo luego del reset"
            git status

            echo "6. Instalando dependencias con npm ci"
            npm ci || { echo 'ERROR: npm ci fall贸'; exit 1; }

            echo "7. Ejecutando build con npm run build"
            npm run build || { echo 'ERROR: npm run build fall贸'; exit 1; }

            echo "8. Listado archivos en carpeta dist"
            ls -l ./dist

            echo "=== Fin Despliegue ==="
