name: Deploy Landing Robust

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "=== Iniciando despliegue ==="
            cd /opt/landing/lumensm-landing-boltai

            git fetch --all
            git reset --hard origin/main

            npm ci
            npm run build

            # Paths
            BUILD_DIR="./dist"
            TARGET="/opt/landing/lumensm-landing-boltai/current"
            BACKUP="/opt/landing/lumensm-landing-boltai/backup_$(date +%Y%m%d%H%M%S)"

            # Backup versión actual
            if [ -d "$TARGET" ]; then
              echo "Creando backup en $BACKUP"
              mv "$TARGET" "$BACKUP"
            fi

            # Crear carpeta destino y copiar nuevo build
            mkdir -p "$TARGET"
            cp -r "$BUILD_DIR"/* "$TARGET/"

            echo "Despliegue completado con éxito."

            # Limpiar backups antiguos (mantener últimos 5)
            echo "Limpiando backups antiguos..."
            ls -dt /opt/landing/lumensm-landing-boltai/backup_* | tail -n +6 | xargs -r rm -rf
            echo "Backups antiguos eliminados."
            echo "=== Fin de despliegue ==="
